server:
  port: 4000

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: false

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

          routes:
            # Auth Service Routes
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:4002}
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: auth-service
                    fallbackUri: forward:/fallback/auth
                - name: RateLimiter
                  args:
                    requestsPerSecond: 100
                    burstCapacity: 200
                - RewritePath=/api/v1/auth/(?<segment>.*), /auth-service/api/v1/auth/${segment}

            # Auth Service Documentation Routes - Direct auth-service paths (for absolute URLs in swagger config)
            - id: auth-service-direct-paths
              uri: ${AUTH_SERVICE_URL:http://localhost:4002}
              predicates:
                - Path=/auth-service/**
              filters:
                - StripPrefix=0

            # Auth Service Documentation Routes - Catch all for docs
            - id: auth-service-docs-catchall
              uri: ${AUTH_SERVICE_URL:http://localhost:4002}
              predicates:
                - Path=/auth-docs/**
              filters:
                - RewritePath=/auth-docs/(?<segment>.*), /auth-service/$\{segment}
                - AddRequestHeader=X-Forwarded-Proto, http
                - AddRequestHeader=X-Forwarded-Host, localhost:4000
                - AddRequestHeader=X-Forwarded-Port, 4000
                - AddRequestHeader=X-Forwarded-Prefix, /auth-docs

            # Auth Service Documentation Routes - Root redirect
            - id: auth-service-docs-root
              uri: no://op
              predicates:
                - Path=/auth-docs
              filters:
                - RedirectTo=302, /auth-docs/swagger-ui/index.html

            # Tenant Service Routes
            - id: tenant-service
              uri: ${TENANT_SERVICE_URL:http://localhost:4001}
              predicates:
                - Path=/api/v1/tenants/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: tenant-service
                    fallbackUri: forward:/fallback/tenant
                - name: RateLimiter
                  args:
                    requestsPerSecond: 50
                    burstCapacity: 100
                - AuthenticationFilter
                - StripPrefix=2

            # Authorization Service Routes
            - id: authorization-service
              uri: ${AUTHZ_SERVICE_URL:http://localhost:4003}
              predicates:
                - Path=/api/v1/authorization/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: authorization-service
                    fallbackUri: forward:/fallback/authorization
                - name: RateLimiter
                  args:
                    requestsPerSecond: 100
                    burstCapacity: 200
                - AuthenticationFilter
                - StripPrefix=2

            # User Management Service Routes
            - id: user-management-service
              uri: ${USER_SERVICE_URL:http://localhost:4004}
              predicates:
                - Path=/api/v1/users/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: user-service
                    fallbackUri: forward:/fallback/user
                - name: RateLimiter
                  args:
                    requestsPerSecond: 50
                    burstCapacity: 100
                - AuthenticationFilter
                - StripPrefix=2

            # Notification Service Routes
            - id: notification-service
              uri: ${NOTIFICATION_SERVICE_URL:http://localhost:4402}
              predicates:
                - Path=/api/v1/notifications/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: notification-service
                    fallbackUri: forward:/fallback/notification
                - name: RateLimiter
                  args:
                    requestsPerSecond: 30
                    burstCapacity: 60
                - AuthenticationFilter
                - StripPrefix=2

            # Storage Service Routes
            - id: storage-service
              uri: ${STORAGE_SERVICE_URL:http://localhost:4102}
              predicates:
                - Path=/api/v1/storage/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: storage-service
                    fallbackUri: forward:/fallback/storage
                - name: RateLimiter
                  args:
                    requestsPerSecond: 20
                    burstCapacity: 40
                - AuthenticationFilter
                - StripPrefix=2
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:3000"
                  - "http://localhost:8080"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true
                maxAge: 3600

# Rate Limiting Configuration
rate-limiting:
  enabled: true
  default:
    requests-per-second: 100
    burst-capacity: 200
  per-tenant:
    enabled: true
    cache-size: 10000

# Resilience4j Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - java.io.IOException
          - java.net.ConnectException
          - java.util.concurrent.TimeoutException
    instances:
      auth-service:
        baseConfig: default
      tenant-service:
        baseConfig: default
      authorization-service:
        baseConfig: default
      user-service:
        baseConfig: default
      notification-service:
        baseConfig: default
      storage-service:
        baseConfig: default
      auth-service-docs:
        baseConfig: default

  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - java.io.IOException
          - java.net.ConnectException
    instances:
      auth-service:
        baseConfig: default
      tenant-service:
        baseConfig: default

# Monitoring Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    com.nnipa.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    io.github.resilience4j: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - [%X{correlationId}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - [%thread] - [%X{correlationId}] - %-5level %logger{36} - %msg%n"
  file:
    name: logs/api-gateway.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# API Documentation Configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway
      - url: /auth-docs/api-docs
        name: Auth Service
      - url: ${TENANT_SERVICE_URL:http://localhost:4001}/api-docs
        name: Tenant Service

# Custom API Gateway Configuration
api-gateway:
  security:
    jwt-secret: ${JWT_SECRET:dGhpcyBpcyBhIDUxMi1iaXQgc2VjcmV0IGtleSBmb3IgSFM1MTIgand0IHNpZ25pbmcgYWxnb3JpdGhtIGVuY29kZWQgaW4gYmFzZTY0IGZvcm1hdCB0aGF0IHlvdSBjYW4gdXNlIGZvciBzZWN1cmUgdG9rZW4=}
    jwt-issuer: ${JWT_ISSUER:https://nnipa.cloud}
    public-paths:
      - /api/v1/auth/register
      - /api/v1/auth/login
      - /api/v1/auth/refresh
      - /api/v1/auth/forgot-password
      - /api/v1/auth/reset-password
      - /actuator/health
      - /actuator/prometheus
      - /swagger-ui/**
      - /v3/api-docs/**
      - /auth-docs/**
      - /auth-service/**
  rate-limiting:
    enabled: true
    default-limits:
      requests-per-second: 100
      burst-capacity: 200
    per-tenant-enabled: true
    cache-size: 10000
  correlation:
    header-name: X-Correlation-Id
    generate-if-missing: true