server:
  port: 4000

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: false

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

          routes:
            # Auth Service Routes
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:4002}
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: auth-service
                    fallbackUri: forward:/fallback/auth
                - name: RateLimiter
                  args:
                    requestsPerSecond: 100
                    burstCapacity: 200
                - RewritePath=/api/v1/auth/(?<segment>.*), /auth-service/api/v1/auth/${segment}
              metadata:
                # Route-specific timeout
                response-timeout: 5000
                connect-timeout: 2000

            # Auth Service Documentation Routes - Direct auth-service paths (for absolute URLs in swagger config)
            - id: auth-service-direct-paths
              uri: ${AUTH_SERVICE_URL:http://localhost:4002}
              predicates:
                - Path=/auth-service/**
              filters:
                - StripPrefix=0

            # Auth Service Documentation Routes - Catch all for docs
            - id: auth-service-docs-catchall
              uri: ${AUTH_SERVICE_URL:http://localhost:4002}
              predicates:
                - Path=/auth-docs/**
              filters:
                - RewritePath=/auth-docs/(?<segment>.*), /auth-service/${segment}
                - AddRequestHeader=X-Forwarded-Proto, http
                - AddRequestHeader=X-Forwarded-Host, localhost:4000
                - AddRequestHeader=X-Forwarded-Port, 4000
                - AddRequestHeader=X-Forwarded-Prefix, /auth-docs

            # Auth Service Documentation Routes - Root redirect
            - id: auth-service-docs-root
              uri: no://op
              predicates:
                - Path=/auth-docs
              filters:
                - RedirectTo=302, /auth-docs/swagger-ui/index.html

            # Tenant Service Routes
            - id: tenant-service
              uri: ${TENANT_SERVICE_URL:http://localhost:4001}
              predicates:
                - Path=/api/v1/tenants/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: tenant-service
                    fallbackUri: forward:/fallback/tenant
                - name: RateLimiter
                  args:
                    requestsPerSecond: 50
                    burstCapacity: 100
                - AuthenticationFilter
                - StripPrefix=2

            # Tenant Service Documentation Routes - Handle direct tenant-management paths (for Swagger UI redirects)
            - id: tenant-service-management-paths
              uri: ${TENANT_SERVICE_URL:http://localhost:4001}
              predicates:
                - Path=/tenant-management/**
              filters:
                - StripPrefix=0

            # Tenant Service Documentation Routes - Direct tenant-service paths (for absolute URLs in swagger config)
            - id: tenant-service-direct-paths
              uri: ${TENANT_SERVICE_URL:http://localhost:4001}
              predicates:
                - Path=/tenant-service/**
              filters:
                - StripPrefix=0

            # Tenant Service Documentation Routes - Catch all for docs
            - id: tenant-service-docs-catchall
              uri: ${TENANT_SERVICE_URL:http://localhost:4001}
              predicates:
                - Path=/tenant-docs/**
              filters:
                - RewritePath=/tenant-docs/(?<segment>.*), /tenant-management/${segment}
                - AddRequestHeader=X-Forwarded-Proto, http
                - AddRequestHeader=X-Forwarded-Host, localhost:4000
                - AddRequestHeader=X-Forwarded-Port, 4000
                - AddRequestHeader=X-Forwarded-Prefix, /tenant-docs

            # Tenant Service Documentation Routes - Root redirect
            - id: tenant-service-docs-root
              uri: no://op
              predicates:
                - Path=/tenant-docs
              filters:
                - RedirectTo=302, /tenant-docs/swagger-ui/index.html

            # Tenant Service Health Check Route (optional - for direct access through gateway)
            - id: tenant-service-health
              uri: ${TENANT_SERVICE_URL:http://localhost:4001}
              predicates:
                - Path=/tenant-health/**
              filters:
                - RewritePath=/tenant-health/(?<segment>.*), /tenant-management/actuator/${segment}

            # ==============================================
            # AUTHORIZATION SERVICE ROUTES (FIXED)
            # ==============================================

            # Primary Authorization Service Routes - Fixed to include context path
            - id: authorization-service
              uri: ${AUTHZ_SERVICE_URL:http://localhost:4003}
              predicates:
                - Path=/api/v1/authz/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: authorization-service
                    fallbackUri: forward:/fallback/authorization
                - name: RateLimiter
                  args:
                    requestsPerSecond: 200
                    burstCapacity: 400
                - AuthenticationFilter
                - RewritePath=/api/v1/authz/(?<segment>.*), /authz/api/v1/authz/${segment}
              metadata:
                response-timeout: 3000
                connect-timeout: 1500

            # Authorization Service Routes - Legacy compatibility (fixed)
            - id: authorization-service-legacy
              uri: ${AUTHZ_SERVICE_URL:http://localhost:4003}
              predicates:
                - Path=/api/v1/authorization/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: authorization-service
                    fallbackUri: forward:/fallback/authorization
                - name: RateLimiter
                  args:
                    requestsPerSecond: 200
                    burstCapacity: 400
                - AuthenticationFilter
                - RewritePath=/api/v1/authorization/(?<segment>.*), /authz/api/v1/authz/${segment}
              metadata:
                response-timeout: 3000
                connect-timeout: 1500

            # Authorization Service Documentation Routes - Fixed context path
            - id: authz-service-direct-paths
              uri: ${AUTHZ_SERVICE_URL:http://localhost:4003}
              predicates:
                - Path=/authz-service/**
              filters:
                - RewritePath=/authz-service/(?<segment>.*), /authz/${segment}
                - AddRequestHeader=X-Forwarded-Proto, http
                - AddRequestHeader=X-Forwarded-Host, localhost:4000
                - AddRequestHeader=X-Forwarded-Port, 4000

            # Authorization Service Documentation Routes - Fixed rewrite
            - id: authz-service-docs-catchall
              uri: ${AUTHZ_SERVICE_URL:http://localhost:4003}
              predicates:
                - Path=/authz-docs/**
              filters:
                - RewritePath=/authz-docs/(?<segment>.*), /authz/${segment}
                - AddRequestHeader=X-Forwarded-Proto, http
                - AddRequestHeader=X-Forwarded-Host, localhost:4000
                - AddRequestHeader=X-Forwarded-Port, 4000
                - AddRequestHeader=X-Forwarded-Prefix, /authz-docs

            # Authorization Service Documentation Routes - Root redirect (fixed)
            - id: authz-service-docs-root
              uri: no://op
              predicates:
                - Path=/authz-docs
              filters:
                - RedirectTo=302, /authz-docs/swagger-ui/index.html

            # Authorization Service Documentation Routes - Static resources fallback
            - id: authz-service-docs-static
              uri: ${AUTHZ_SERVICE_URL:http://localhost:4003}
              predicates:
                - Path=/authz-docs/swagger-ui/**
              filters:
                - RewritePath=/authz-docs/swagger-ui/(?<segment>.*), /authz/swagger-ui/${segment}
                - AddRequestHeader=X-Forwarded-Proto, http
                - AddRequestHeader=X-Forwarded-Host, localhost:4000
                - AddRequestHeader=X-Forwarded-Port, 4000

            # Authorization Service Health Check Route - Fixed context path
            - id: authz-service-health
              uri: ${AUTHZ_SERVICE_URL:http://localhost:4003}
              predicates:
                - Path=/authz-health/**
              filters:
                - RewritePath=/authz-health/(?<segment>.*), /authz/actuator/${segment}

            # Authorization Service - Admin routes (fixed context path)
            - id: authz-service-admin
              uri: ${AUTHZ_SERVICE_URL:http://localhost:4003}
              predicates:
                - Path=/api/v1/authz/admin/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: authorization-service
                    fallbackUri: forward:/fallback/authorization
                - name: RateLimiter
                  args:
                    requestsPerSecond: 50
                    burstCapacity: 100
                - AuthenticationFilter
                - RewritePath=/api/v1/authz/admin/(?<segment>.*), /authz/api/v1/authz/admin/${segment}
              metadata:
                response-timeout: 5000
                connect-timeout: 2000

            # Authorization Service Documentation Routes - Direct Swagger UI access (ADD THIS)
            - id: authz-service-swagger-ui-direct
              uri: ${AUTHZ_SERVICE_URL:http://localhost:4003}
              predicates:
                - Path=/authz/swagger-ui/**
              filters:
                - StripPrefix=0

            # Authorization Service Documentation Routes - Direct API docs access (ADD THIS)
            - id: authz-service-api-docs-direct
              uri: ${AUTHZ_SERVICE_URL:http://localhost:4003}
              predicates:
                - Path=/authz/v3/api-docs/**
              filters:
                - StripPrefix=0

            # Authorization Service Documentation Routes - API docs root path (ADD THIS)
            - id: authz-service-api-docs-root
              uri: ${AUTHZ_SERVICE_URL:http://localhost:4003}
              predicates:
                - Path=/authz/api-docs/**
              filters:
                - StripPrefix=0

            # Authorization Service Documentation Routes - Direct webjars access (ADD THIS)
            - id: authz-service-webjars-direct
              uri: ${AUTHZ_SERVICE_URL:http://localhost:4003}
              predicates:
                - Path=/authz/webjars/**
              filters:
                - StripPrefix=0

            # User Management Service Routes
            - id: user-management-service
              uri: ${USER_SERVICE_URL:http://localhost:4004}
              predicates:
                - Path=/api/v1/users/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: user-service
                    fallbackUri: forward:/fallback/user
                - name: RateLimiter
                  args:
                    requestsPerSecond: 50
                    burstCapacity: 100
                - AuthenticationFilter
                - StripPrefix=2

            # User Management Service Documentation Routes
            - id: user-service-direct-paths
              uri: ${USER_SERVICE_URL:http://localhost:4004}
              predicates:
                - Path=/user-service/**
              filters:
                - StripPrefix=0

            - id: user-service-docs-catchall
              uri: ${USER_SERVICE_URL:http://localhost:4004}
              predicates:
                - Path=/user-docs/**
              filters:
                - RewritePath=/user-docs/(?<segment>.*), /${segment}
                - AddRequestHeader=X-Forwarded-Proto, http
                - AddRequestHeader=X-Forwarded-Host, localhost:4000
                - AddRequestHeader=X-Forwarded-Port, 4000
                - AddRequestHeader=X-Forwarded-Prefix, /user-docs

            - id: user-service-docs-root
              uri: no://op
              predicates:
                - Path=/user-docs
              filters:
                - RedirectTo=302, /user-docs/swagger-ui.html

            - id: user-service-health
              uri: ${USER_SERVICE_URL:http://localhost:4004}
              predicates:
                - Path=/user-health/**
              filters:
                - RewritePath=/user-health/(?<segment>.*), /actuator/${segment}

            # Notification Service Routes
            - id: notification-service
              uri: ${NOTIFICATION_SERVICE_URL:http://localhost:4402}
              predicates:
                - Path=/api/v1/notifications/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: notification-service
                    fallbackUri: forward:/fallback/notification
                - name: RateLimiter
                  args:
                    requestsPerSecond: 30
                    burstCapacity: 60
                - AuthenticationFilter
                - StripPrefix=2

            # Storage Service Routes
            - id: storage-service
              uri: ${STORAGE_SERVICE_URL:http://localhost:4102}
              predicates:
                - Path=/api/v1/storage/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: storage-service
                    fallbackUri: forward:/fallback/storage
                - name: RateLimiter
                  args:
                    requestsPerSecond: 20
                    burstCapacity: 40
                - AuthenticationFilter
                - StripPrefix=2

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:3000"
                  - "http://localhost:8080"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true
                maxAge: 3600

# Rate Limiting Configuration
rate-limiting:
  enabled: true
  default:
    requests-per-second: 100
    burst-capacity: 200
  per-tenant:
    enabled: true
    cache-size: 10000

# Resilience4j Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - java.io.IOException
          - java.net.ConnectException
          - java.util.concurrent.TimeoutException
    instances:
      auth-service:
        baseConfig: default
        waitDurationInOpenState: 30000  # 30 seconds for auth service
        minimumNumberOfCalls: 3         # Reduce for faster circuit breaker activation
        failureRateThreshold: 60        # Allow slightly more failures
      tenant-service:
        baseConfig: default
      authorization-service:
        baseConfig: default
        failureRateThreshold: 70        # More tolerant for frequent authorization calls
        slidingWindowSize: 15           # Larger sample size for better accuracy
        minimumNumberOfCalls: 8         # Higher threshold before circuit opens
      user-service:
        baseConfig: default
      notification-service:
        baseConfig: default
      storage-service:
        baseConfig: default
      auth-service-docs:
        baseConfig: default

  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - java.io.IOException
          - java.net.ConnectException
    instances:
      auth-service:
        baseConfig: default
      tenant-service:
        baseConfig: default
      authorization-service:
        maxAttempts: 2
        waitDuration: 500  # Faster retry for authorization service

  # Add timeout configuration
  timelimiter:
    configs:
      default:
        timeoutDuration: 3000  # 3 seconds default
        cancelRunningFuture: true
    instances:
      auth-service:
        baseConfig: default
        timeoutDuration: 5000  # 5 seconds for auth operations
      tenant-service:
        baseConfig: default
        timeoutDuration: 4000  # 4 seconds for tenant operations
      authorization-service:
        baseConfig: default
        timeoutDuration: 3000  # Fast timeout for authorization checks

# Monitoring Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    com.nnipa.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    io.github.resilience4j: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - [%X{correlationId}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - [%thread] - [%X{correlationId}] - %-5level %logger{36} - %msg%n"
  file:
    name: logs/api-gateway.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# API Documentation Configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway
      - url: /auth-docs/api-docs
        name: Authentication Service
      - url: /authz-docs/api-docs
        name: Authorization Service
      - url: /tenant-docs/api-docs
        name: Tenant Management Service
      - url: /user-docs/api-docs
        name: User Management Service

# Custom API Gateway Configuration
api-gateway:
  security:
    jwt-secret: ${JWT_SECRET:dGhpcyBpcyBhIDUxMi1iaXQgc2VjcmV0IGtleSBmb3IgSFM1MTIgand0IHNpZ25pbmcgYWxnb3JpdGhtIGVuY29kZWQgaW4gYmFzZTY0IGZvcm1hdCB0aGF0IHlvdSBjYW4gdXNlIGZvciBzZWN1cmUgdG9rZW4=}
    jwt-issuer: ${JWT_ISSUER:https://nnipa.cloud}
    public-paths:
      - /api/v1/auth/register
      - /api/v1/auth/login
      - /api/v1/auth/refresh
      - /api/v1/auth/forgot-password
      - /api/v1/auth/reset-password
      - /actuator/health
      - /actuator/prometheus
      - /swagger-ui/**
      - /v3/api-docs/**
      - /auth-docs/**
      - /auth-service/**
      - /authz-docs/**
      - /authz-service/**
      - /authz-health/**
      - /tenant-docs/**
      - /tenant-service/**
      - /tenant-health/**
      - /tenant-management/**
      - /user-docs/**
      - /user-service/**
      - /user-health/**
  rate-limiting:
    enabled: true
    default-limits:
      requests-per-second: 100
      burst-capacity: 200
    per-tenant-enabled: true
    cache-size: 10000
  correlation:
    header-name: X-Correlation-Id
    generate-if-missing: true